### ISSUE TITLE
Consolidate Repositories

### ISSUE THREAD

**Issue by tordans** [jbelien/osm-compare#74]
There is this repo and there is https://github.com/osmbe/osm-compare/.

I find this confusing and suggest to github-archive the https://github.com/osmbe/osm-compare/ so only this one stay aktive.

This change would make it easier to understand the code. Last year I was confused and wrote 
 https://github.com/jbelien/osm-compare/issues/54. Now the two repos are out of sync, the osmbe has the updated readme but this one has the security updates … (I created https://github.com/jbelien/osm-compare/pull/75 to sync them again).

**Comment by jbelien** [comment]
Done!
Thanks for the notice.
